### ISSUE TITLE
SKU?

### ISSUE THREAD

**Issue by theheatDK** [MicrosoftDocs/partner-center-sdk#27]
Hi,
When you use the Azure pricing calculator you can export you estimated monthly costs to a spreadsheet. You can choose to include the SKUs in the file.  For a D2 v3 VM you get "AAA-44939, N9H-00920, N9H-01263".
How do I extract the SKUs via the Rate Card API?
Regards Peter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d9bd51a-02cd-7042-e95b-d6a200ca6879
* Version Independent ID: cc461259-77f6-94e7-c940-22396b4a74ab
* Content: [Get prices for Microsoft Azure - Partner Center app developer](https://docs.microsoft.com/en-us/partner-center/develop/get-prices-for-microsoft-azure)
* Content Source: [develop/get-prices-for-microsoft-azure.md](https://github.com/MicrosoftDocs/partner-center-sdk/blob/docs/develop/get-prices-for-microsoft-azure.md)
* Product: **partner-center**
* Technology: **partner-center-sdk**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by isaiahwilliams** [comment]
The rate card feature of the API will return all the billable meters for Azure. Since you do not have the exact meter identifier, then you will need to look for the meter with the name that match the SKU. Note the rate card feature is typically used with the Azure utilization records to calculate the price. While you can use this feature for a number of other methods, it makes the most sense when working with Azure utilization records. 

In the next few weeks we plan to launch a new price list feature. That will make this task much easier.
